### ISSUE TITLE
The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by TDola** [kotarella1110/cordova-plugin-webpack#14]
```
C:\workspace\github\appName>cordova prepare -- --livereload
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.basename (path.js:744:5)
    at module.exports (C:\workspace\github\appName\plugins\cordova-plugin-webpack\node_modules\rechoir\lib\extension.js:7:23)
    at Object.exports.prepare (C:\workspace\github\appName\plugins\cordova-plugin-webpack\node_modules\rechoir\index.js:11:14)
    at Object.exports.webpackConfig (C:\workspace\github\appName\plugins\cordova-plugin-webpack\src\utils\webpackHelper.ts:32:11)
    at Object.<anonymous> (C:\workspace\github\appName\plugins\cordova-plugin-webpack\src\webpackServe.ts:66:70)
    at step (C:\workspace\github\appName\plugins\cordova-plugin-webpack\scripts\webpackServe.js:43:23)
    at Object.next (C:\workspace\github\appName\plugins\cordova-plugin-webpack\scripts\webpackServe.js:24:53)
    at fulfilled (C:\workspace\github\appName\plugins\cordova-plugin-webpack\scripts\webpackServe.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Got this error on Windows right after installing the plugin.  Unsure what to do to fix it.

This is using Vue, so my webpack files are:
"C:\workspace\github\appName\build\webpack.prod.conf.js"
"C:\workspace\github\appName\build\webpack.base.conf.js"
"C:\workspace\github\appName\build\webpack.dev.conf.js"
"C:\workspace\github\appName\config\test.env.js"
"C:\workspace\github\appName\config\dev.env.js"
"C:\workspace\github\appName\config\index.js"
"C:\workspace\github\appName\config\prod.env.js"

The Vue documentation says I am to use this path
`<projectRoot>/node_modules/@vue/cli-service/webpack.config.js`

**Comment by kotarella1110** [comment]
@TDola Have you tried `--webpackConfig` option ?

```shell
cordova prepare -- --webpackConfig node_modules/@vue/cli-service/webpack.config.js --livereload
```

If the problem persists, can you attach the code?

Thanks.

**Comment by TDola** [comment]
New problem, this time its vue-cli's fault.  This one is solved.  Thank you
