### ISSUE TITLE
Support the browser platform?

### ISSUE THREAD

**Issue by MichaelPeterJoyce** [kotarella1110/cordova-plugin-webpack#15]
Hi i was wondering is it possible to support to Browser platform to have live HMR in the browser

The emulators are very slow on my machine and having this working in the browser would be perfect!

**Comment by kotarella1110** [comment]
Hi @MichaelPeterJoyce ,this plugin does not support livereload in the browser.
I will work to support the browser platform as soon as possible!
I'll report here if there is any progress.

**Comment by kotarella1110** [comment]
Hi @MichaelPeterJoyce !

I just committed to add support for LiveReload (HMR).
Please try the following.

Install the latest plugin for the develop branch.

```shell
$ cordova plugin add https://github.com/kotarella1110/cordova-plugin-webpack.git#develop
or
$ cordova plugin add git@github.com:kotarella1110/cordova-plugin-webpack.git#develop
```

Execute the commands.

```shell
$ cordova run browser -- --livereload
or
$ cordova run browser -- -l
```
If it works well, I would like to publish to npm.

**Comment by kotarella1110** [comment]
Earlier, v0.4.0 was released.
Therefore, please install the plugin from npm.

```shell
$ cordova plugin add cordova-plugin-webpack
```

**Comment by MichaelPeterJoyce** [comment]
Hi thanks for the update! I have checked it out but unfortunately i can't get the live reload working in the browser.

I see when i run cordova run browser -- -l there are two servers running 

1. webpack-dev-server on port 8080
2. cordova browser static file server running on port 8000

I can't access my application via 8080 because of its heavy use of cordova.js because webpack-dev-server doesn't inject the cordova dependency then my app won't load and the deviceready event is never fired because cordova is never loaded.

If i access the app via port 8000 on the local cordova browser server then everything works fine because cordova.js is injected and the deviceready event is fired but there is no hot module reloading working

Hopefully this makes sense 

Thanks again

**Comment by kotarella1110** [comment]
> Nevermind the above i didn't realize i needed to update my <meta http-equiv="Content-Security-Policy" to allow the injection of the script.

How did you update your Content Security Policy?
For our reference, please let us know.

> This seems to be working but it doesn't inject any of the plugins.
> Is there anyway you can make it inject the plugins like the browser platform?

The `cordova.js` file is loaded by this plugin depending on the platform as follows:

* Browser (Desktop): `platforms/browser/platform_www/cordova.js`
* Android device (Browser and WebView): `platforms/android/platform_www/cordova.js`
* iOS device (Browser and WebView): `platforms/ios/platform_www/cordova.js`

However, the mobile browsers needs to load the `platforms/browser/platform_www/cordova.js` file as follows:

* Browser (Desktop and Mobile device): `platforms/browser/platform_www/cordova.js`
* Android device (WebView only): `platforms/android/platform_www/cordova.js`
* iOS device (WebView only): `platforms/ios/platform_www/cordova.js`

This fix needs to be able to detect mobile browser or WebView.
I confirm when this fix is ​​possible or not.

Thanks.

**Comment by kotarella1110** [comment]
Earlier, v0.4.1 was released.
Therefore, please install the plugin from npm.

```shell
$ cordova plugin add cordova-plugin-webpack
```

**Comment by mese79** [comment]
Hi  
When I try this `$ cordova run browser -- -l`  I've got error:  
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.basename (path.js:1149:5)
    at module.exports (/home/mehdi/Projects/MajdAb/Measurement/mobile_app/sanjesh_app/cordova/node_modules/rechoir/lib/extension.js:7:23)
    at Object.exports.prepare (/home/mehdi/Projects/MajdAb/Measurement/mobile_app/sanjesh_app/cordova/node_modules/rechoir/index.js:11:14)
    at Object.exports.webpackConfig (/home/mehdi/Projects/MajdAb/Measurement/mobile_app/sanjesh_app/cordova/plugins/cordova-plugin-webpack/src/utils/webpackHelpers.ts:32:11)
    at Object.<anonymous> (/home/mehdi/Projects/MajdAb/Measurement/mobile_app/sanjesh_app/cordova/plugins/cordova-plugin-webpack/src/webpackServe.ts:29:71)
    at step (/home/mehdi/Projects/MajdAb/Measurement/mobile_app/sanjesh_app/cordova/plugins/cordova-plugin-webpack/scripts/webpackServe.js:43:23)
    at Object.next (/home/mehdi/Projects/MajdAb/Measurement/mobile_app/sanjesh_app/cordova/plugins/cordova-plugin-webpack/scripts/webpackServe.js:24:53)
    at /home/mehdi/Projects/MajdAb/Measurement/mobile_app/sanjesh_app/cordova/plugins/cordova-plugin-webpack/scripts/webpackServe.js:18:71
    at new Promise (<anonymous>)
```

**Comment by kotarella1110** [comment]
Hi @mese79 ! Did you create webpack configuration file (`webpack.config.js`)  in your project root folder (`/home/mehdi/Projects/MajdAb/Measurement/mobile_app/sanjesh_app/cordova`)?
You can also use `--webpackConfig` or `-w` option.

```shell
$ cordova run browser -- -w path/to/dir/webpack.config.js -l
```

If your problem persists, It seems that your problem has nothing to do with this issue, so please attach the code and  open a new issue.

Thanks.

**Comment by mese79** [comment]
Ok, I see.
I thought it would work without `webpack.config.js`.
Thanks.

**Comment by kotarella1110** [comment]
@MichaelPeterJoyce Did you solve this problem?

**Comment by kotarella1110** [comment]
Closing due to inactivity. Reopen as needed.

**Comment by MichaelPeterJoyce** [comment]
Sorry i was on Holidays.

This works now on the browser platform! YEY but CPU usage is crazy it sticks at 100% CPU usage and all my fans in 2019 iMac spin at 100% this doesn't happen if i run webpack-dev-server manually is there something that you can look at while running the browser platform for CPU usage?

In regards to the Content-Security-Policy above i needed

<meta http-equiv="Content-Security-Policy" content="
                default-src * 'unsafe-inline' 'unsafe-eval';
                script-src * 'self' filesystem: * 'unsafe-inline' 'unsafe-eval' cdvfile: *;">

**Comment by kotarella1110** [comment]
@MichaelPeterJoyce Sorry, I haven't noticed your post.

> This works now on the browser platform! YEY but CPU usage is crazy it sticks at 100% CPU usage and all my fans in 2019 iMac spin at 100% this doesn't happen if i run webpack-dev-server manually is there something that you can look at while running the browser platform for CPU usage?


Please tell me the process that is running over 100% CPU usage.
Isn't the process Code Helper (VSCode)?
This problem occurs even if you are not using this plugin.

> In regards to the Content-Security-Policy above i needed

Thanks!
