### ISSUE TITLE
Browser platform a requirement?

### ISSUE THREAD

**Issue by JimmyMultani** [kotarella1110/cordova-plugin-webpack#16]
It seems like since updating to the latest version, the plugin now requires the `browser` platform.

Is there a way to get around this? Thanks.

```bash
Error: ENOENT: no such file or directory, open '/Users/jimmymultani/Projects/evree/webapp/platforms/browser/www/index.html'
    at Object.openSync (fs.js:438:3)
    at Object.writeFileSync (fs.js:1189:35)
    at /Users/jimmymultani/Projects/evree/webapp/plugins/cordova-plugin-webpack/src/webpackServe.ts:104:12
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/jimmymultani/Projects/evree/webapp/plugins/cordova-plugin-webpack/src/webpackServe.ts:99:15)
    at step (/Users/jimmymultani/Projects/evree/webapp/plugins/cordova-plugin-webpack/scripts/webpackServe.js:43:23)
    at Object.next (/Users/jimmymultani/Projects/evree/webapp/plugins/cordova-plugin-webpack/scripts/webpackServe.js:24:53)
    at fulfilled (/Users/jimmymultani/Projects/evree/webapp/plugins/cordova-plugin-webpack/scripts/webpackServe.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webapp@1.42.0 start: `NODE_ENV=development cordova run --debug --cordova -- -l`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webapp@1.42.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kotarella1110** [comment]
@JimmyMultani Thank you for your feedback!
Sorry, there is no way to get around this because of a bug.

I will fix this bug soon!
Thanks.

**Comment by kotarella1110** [comment]
@JimmyMultani I just committed to fix this bug!
Could you please check?
Install the latest plugin for the develop branch.

**Comment by JimmyMultani** [comment]
Yup, that solved it. Thank you @kotarella1110!

**Comment by kotarella1110** [comment]
@JimmyMultani Just now, v0.4.2 was released!
