### ISSUE TITLE
error after install when running `serve`

### ISSUE THREAD

**Issue by xloem** [kotarella1110/cordova-plugin-webpack#40]
```
(node:23601) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /home/karl/brainstem/fabric-of-reality/phonegap-spacetime/plugins/cordova-plugin-webpack/src/webpackCompile.ts:15:57
    at Array.some (<anonymous>)
    at /home/karl/brainstem/fabric-of-reality/phonegap-spacetime/plugins/cordova-plugin-webpack/src/webpackCompile.ts:15:18
    at step (/home/karl/brainstem/fabric-of-reality/phonegap-spacetime/plugins/cordova-plugin-webpack/dist/webpackCompile.js:33:23)
    at Object.next (/home/karl/brainstem/fabric-of-reality/phonegap-spacetime/plugins/cordova-plugin-webpack/dist/webpackCompile.js:14:53)
    at /home/karl/brainstem/fabric-of-reality/phonegap-spacetime/plugins/cordova-plugin-webpack/dist/webpackCompile.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/karl/brainstem/fabric-of-reality/phonegap-spacetime/plugins/cordova-plugin-webpack/dist/webpackCompile.js:4:12)
    at module.exports (/home/karl/brainstem/fabric-of-reality/phonegap-spacetime/plugins/cordova-plugin-webpack/src/webpackCompile.ts:13:37)
    at runScriptViaModuleLoader (/home/karl/brainstem/fabric-of-reality/phonegap-spacetime/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
(node:23601) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:23601) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is phonegap wrapping cordova.

**Comment by kotarella1110** [comment]
@xloem I will look into this!
